plugins {
    id 'com.android.library'
    id 'org.jetbrains.kotlin.android'
    id 'org.jetbrains.kotlin.plugin.compose'
    id 'kotlin-kapt'
    id("dagger.hilt.android.plugin")
}

android {
    namespace 'com.ezbuy.home'
    compileSdk = libs.versions.compileSdk.get().toInteger()

    defaultConfig {
        minSdkVersion libs.versions.minSdk.get().toInteger()
        targetSdkVersion libs.versions.compileSdk.get().toInteger()
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
        consumerProguardFiles "consumer-rules.pro"
        vectorDrawables { useSupportLibrary true }
    }

    lintOptions { disable 'Instantiatable' }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
    kotlinOptions { jvmTarget = '17' }

    buildFeatures {
        viewBinding = true
        compose = true
    }

    composeOptions {
        // Compose compiler version compatible with Kotlin 2.2.21
        kotlinCompilerExtensionVersion '1.6.0-alpha08-k2.2.0'
    }

    packagingOptions {
        resources {
            excludes += '/META-INF/{AL2.0,LGPL2.1}'
        }
    }
}

dependencies {
    implementation project(path: ':domain')
    implementation project(path: ':common')

    // AndroidX & Compose
    implementation libs.lifecycle.ktx
    implementation libs.compose.activity
    implementation libs.compose.ui.graphics
    implementation libs.compose.ui.material
    implementation libs.fragment.ktx
    implementation libs.compose.hilt.navigation
    implementation libs.compose.view.model
    implementation libs.compose.lifecycle
    implementation libs.view.pager
    implementation libs.flex.box
    implementation libs.shimmer
    implementation libs.paging
    implementation libs.lottie
    implementation libs.glide
    implementation libs.swipe.to.refresh
    implementation libs.compose.glide
    implementation libs.hilt.core

    // Hilt & Navigation
    kapt libs.hilt.compiler
    implementation libs.navigation.fragment.ktx
    implementation libs.navigation.ui.ktx

    // Misc
    implementation libs.appcompat
    implementation libs.android.core

    // Test
    testImplementation libs.junit.core
    androidTestImplementation libs.junit.test
    androidTestImplementation libs.espresso.core
    implementation libs.hilt.test
    kaptAndroidTest libs.hilt.compiler
    testImplementation(libs.mockk.core)
    testImplementation(libs.mockk.android)
    testImplementation(libs.coroutines.test)
}